apiVersion: v1
kind: ConfigMap
metadata:
  name: genai-text-classifier-config
  namespace: default
  labels:
    app: genai-text-classifier
data:
  spring.profiles.active: "prod"
  spring.application.name: "genai-text-classifier"
  # Add more application properties as needed
  # logging.level.root: "INFO"
  # logging.level.com.petluri: "DEBUG"