spring.application.name=gen-ai-text-classifier
server.port=8080

chatgpt.url=https://api.openai.com/v1/chat/completions
# chatgpt.api.key=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
# chatgpt.api.key=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