{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "genai-text-classifier.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "genai-text-classifier.labels" . | nindent 4 }}
{{- end }}